### ISSUE TITLE
g_tree_foreach: assertion `tree != NULL' failed

### ISSUE THREAD

**Issue by dirtyren** [naemon/naemon-livestatus#28]
When I query the table log, I get this error on naemon.log.
  Any ideas on how to go about this problem? Is some cases, naemon crashes when querying the log table.
   Tks.

[1517501818] g_tree_foreach: assertion `tree != NULL' failed
[1517501818] g_tree_foreach: assertion `tree != NULL' failed
[1517501818] g_tree_foreach: assertion `tree != NULL' failed
[1517501818] g_tree_foreach: assertion `tree != NULL' failed
[1517501818] g_tree_foreach: assertion `tree != NULL' failed
[1517501818] g_tree_foreach: assertion `tree != NULL' failed

**Comment by dirtyren** [comment]
Maybe this stack can help

(gdb) where
#0  0x00000031d9e5eac4 in g_slice_alloc () from /lib64/libglib-2.0.so.0
#1  0x00000031d9e17821 in g_ptr_array_sized_new () from /lib64/libglib-2.0.so.0
#2  0x00000031d9e17896 in g_ptr_array_new_with_free_func () from /lib64/libglib-2.0.so.0
#3  0x00007ffff7d81d3d in neb_cb_resultset_create (callback_type=NEBCALLBACK_LOG_DATA, data=
    0x7ffff7388330) at src/naemon/nebmods.c:366
#4  neb_make_callbacks_full (callback_type=NEBCALLBACK_LOG_DATA, data=0x7ffff7388330)
    at src/naemon/nebmods.c:618
#5  0x00007ffff7d81fdf in neb_make_callbacks (callback_type=<value optimized out>, 
    data=<value optimized out>) at src/naemon/nebmods.c:669
#6  0x00007ffff7d62897 in broker_log_data (type=<value optimized out>, 
    flags=<value optimized out>, attr=<value optimized out>, data=
    0x7fffe40112f0 "g_tree_foreach: assertion `tree != NULL' failed", 
    data_type=<value optimized out>, entry_time=<value optimized out>)
    at src/naemon/broker.c:68
#7  0x00007ffff7d7c836 in write_to_log (buffer=
    0x7fffe40112f0 "g_tree_foreach: assertion `tree != NULL' failed", data_type=1, 
    timestamp=<value optimized out>) at src/naemon/logging.c:106
#8  0x00007ffff7d7c959 in write_to_all_logs (data_type=1, fmt=<value optimized out>)
    at src/naemon/logging.c:122
#9  write_to_logs_and_console (data_type=1, fmt=<value optimized out>)
    at src/naemon/logging.c:145
#10 nm_log (data_type=1, fmt=<value optimized out>) at src/naemon/logging.c:162
#11 0x00007ffff7d7ca11 in nm_g_log_handler (domain=<value optimized out>, log_level=
    G_LOG_LEVEL_CRITICAL, message=
    0x7fffe4011250 "g_tree_foreach: assertion `tree != NULL' failed", 
    udata=<value optimized out>) at src/naemon/logging.c:334
#12 0x00000031d9e4b589 in g_logv () from /lib64/libglib-2.0.so.0
#13 0x00000031d9e4b9a3 in g_log () from /lib64/libglib-2.0.so.0
#14 0x00007ffff6fe1882 in HostlistColumn::output (this=0x205e210, data=0x7fffe7103a90, query=
    0x7ffff7388ba0) at HostlistColumn.cc:82
#15 0x00007ffff6fe6203 in Query::printRow (this=0x7ffff7388ba0, data=0x7fffe7103a90)
    at Query.cc:993
#16 0x00007ffff6feaa43 in Query::processDataset (this=0x7ffff7388ba0, data=0x7fffe7103a90)
    at Query.cc:977
#17 0x00007ffff7010933 in Logfile::answerQueryReverse (this=0x20e55d0, query=0x7ffff7388ba0, 
    tablelog=<value optimized out>, since=0, until=<value optimized out>, 
---Type <return> to continue, or q <return> to quit---
    logclasses=<value optimized out>) at Logfile.cc:239
#18 0x00007ffff7011530 in TableLog::answerQuery (this=0xbb0368, query=0x7ffff7388ba0)
    at TableLog.cc:211
#19 0x00007ffff6fed656 in Store::answerGetRequest (this=0xbafe20, input=0x7fffe40008c0, 
    output=0x7fffe4010ba0, tablename=0x7fffe4010c1c "log") at Store.cc:191
#20 0x00007ffff6fed99a in Store::answerRequest (this=0xbafe20, input=0x7fffe40008c0, output=
    0x7fffe4010ba0) at Store.cc:131
#21 0x00007ffff6fecb09 in store_answer_request (ib=<value optimized out>, 
    ob=<value optimized out>) at store.cc:80
#22 0x00007ffff701932b in client_thread (data=<value optimized out>) at module.c:194
#23 0x00000031d8207aa1 in start_thread () from /lib64/libpthread.so.0
#24 0x00000031d7ee8bcd in clone () from /lib64/libc.so.6

**Comment by dirtyren** [comment]
Closed by #29
