### ISSUE TITLE
EL8: further crash dumps triggered

### ISSUE THREAD

**Issue by pbiering** [naemon/naemon-livestatus#77]
another crash dump hit me, backtrace:

```
#0  0x00007fe86ac44ac5 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007fe868c47931 in Query::outputString(char const*) () from /tmp/livestatus.so
#2  0x00007fe868c4753b in Query::printRow(void*) () from /tmp/livestatus.so
#3  0x00007fe868c4b37a in Query::finish() () from /tmp/livestatus.so
#4  0x00007fe868c4d995 in Store::answerGetRequest(InputBuffer*, OutputBuffer*, char const*) () from /tmp/livestatus.so
#5  0x00007fe868c4dc93 in Store::answerRequest(InputBuffer*, OutputBuffer*) ()
   from /tmp/livestatus.so
#6  0x00007fe868c4d03d in store_answer_request () from /tmp/livestatus.so
#7  0x00007fe868c83e47 in client_thread () from /tmp/livestatus.so
#8  0x00007fe86a2a22de in start_thread () from /lib64/libpthread.so.0
#9  0x00007fe86abe32a3 in clone () from /lib64/libc.so.6
``` 

compiled with clang results in a different "corner case" (customvars) crash

```
2020-06-23 15:05:04 Ignoring invalid UTF-8 sequence in string '▒'
2020-06-23 15:05:04 Ignoring invalid UTF-8 sequence in string '▒'
2020-06-23 15:05:04 Ignoring invalid UTF-8 sequence in string '▒'
2020-06-23 15:05:04 Ignoring invalid UTF-8 sequence in string '▒'
2020-06-23 15:05:04 Ignoring invalid UTF-8 sequence in string '▒'
2020-06-23 15:05:04 Ignoring invalid UTF-8 sequence in string '▒'
2020-06-23 15:05:04 Ignoring invalid UTF-8 sequence in string '▒'
```
backtrace
```
#0  0x00007f46170383c0 in Query::outputString(char const*) () from /tmp/livestatus.so
#1  0x00007f461702f1f2 in CustomVarsColumn::output(void*, Query*) ()
   from /tmp/livestatus.so
#2  0x00007f4617038f12 in Query::printRow(void*) () from /tmp/livestatus.so
#3  0x00007f4617039226 in Query::finish() () from /tmp/livestatus.so
```

I've tried to place several tracing debug statements, it still unclear to me why it crashes, also I can't really check what is the cause, because trying to access the "char const*" will already cause the crash, even if I try to display the first char by e.g. "s[0]" - something really strange.

**Comment by pbiering** [comment]
layer 8 problem, incomplete applied https://github.com/naemon/naemon-livestatus/pull/73 caused this...
